version: '2.1'

services:
  rabbit:
    build: rabbitmq/.
    container_name: rabbit_black
    ports: 
        - "15672:15672"
        - "5672:5672"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 3s
        timeout: 5s
        retries: 20
  postgres:
    build: postgres/.
    container_name: postgres_black
    environment:
      - POSTGRES_USER=black
      - POSTGRES_PASSWORD=black101
      - POSTGRES_DB=black
    ports: 
        - "5432:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 20
  black:
    image: black
    build: .
    ports:
      - 5000:5000
    depends_on:
      rabbit:
        condition: service_healthy      
      postgres:
        condition: service_healthy
