FROM ubuntu:16.04

# If you prefer miniconda:
#FROM continuumio/miniconda3

LABEL Name=front_black Version=1.0.0
EXPOSE 5000

RUN apt-get update
RUN apt-get install -y software-properties-common vim
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

RUN apt install -y \
    build-essential \
    python3.6 \
    python3.6-dev \
    python3-pip \
    sudo

RUN python3.6 -m pip install --upgrade pip

WORKDIR /app
ADD . /app

RUN python3.6 -m pip install -r requirements.txt
RUN python3.6 -m pip install -r black/requirements.txt

CMD ["python3.6", "server.py", "--config", "/app/config/config_docker.yml"]
