FROM ubuntu:16.04

LABEL Name=nmap_black Version=1.0.0

RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update

RUN apt install -y \
    build-essential \
    python3.6 \
    python3.6-dev \
    python3-pip \
    nmap \
    masscan \
    vim \
    sudo

RUN python3.6 -m pip install --upgrade pip

WORKDIR /app
ADD . /app

RUN python3.6 -m pip install -r requirements.txt

CMD ["python3.6", "spawn_worker.py", "patator","--config", "/app/config/config_docker.yml"]