application:
  host: 0.0.0.0
  port: 5000
  auth:
    username: pt
    password: blackisbackfuckers
rabbit:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest
postgres:
  host: 127.0.0.1
  port: 5432
  username: black
  password: black101
  database: black
logs:
  directory: logs/
